# Generated by Django 6.0 on 2025-12-07 15:27

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='session_token',
            field=models.UUIDField(default=uuid.uuid4, editable=False),
        ),
    ]
