# Generated by Django 6.0 on 2025-12-07 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_session_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='user_id',
            field=models.CharField(editable=False, max_length=30, null=True, unique=True),
        ),
    ]
